### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by feffes**
heck ye

### CODE REVIEW

**Comment by knya** [comment]
Suggesting to drop `.gitmodules` so Docker doesn't need to transfer 800MB each time `docker build .` is used.

**Comment by knya** [comment]
`if (UNIX)` in `CMakeLists.txt` might interfere with others configurations. Perhaps rename the system name somehow within Docker and then use `if (${CMAKE_SYSTEM_NAME} Matches "Docker")`

**Comment by feffes** [comment]
@knya Regarding gitmodules, I suggest we fetch the source code when building the image.

@knya Regarding libpaths, I suggest we set those variables depending on if they're set or not, which allows for path overriding in case of differing paths.

**Comment by knya** [comment]
> @knya Regarding gitmodules, I suggest we fetch the source code when building the image.

Yes, that way Docker handles the installation within the container without using `extern`. Correct? 

> @knya Regarding libpaths, I suggest we set those variables depending on if they're set or not, which allows for path overriding in case of differing paths.

That might be the only solution, since Docker resolve to `Linux` when using `${CMAKE_SYSTEM_NAME}` and not sure system names can actually be changed.

**Pull request closed without merging**
